/**
 * Provides Skrifa's functionality.
 *
 * This file contains core functionality for Skrifa, functions and initialValue
 * settings are declared here.
 */


// Show the loading screen with a custom message
function wait(message){
	$_('[data-view]').removeClass("active");
	$_('[data-view="loading"] h2').text(message);
	$_('[data-view="loading"]').addClass("active");
}

// Show a given view
function show(view){
	$_('[data-view]').removeClass("active");
	$_('[data-view="' + view + '"]').addClass("active");
}

function encrypt(data, options){
	if(typeof options == 'undefined'){
		encryptOptions.data = data;
		return openpgp.encrypt(encryptOptions);
	}else{
		options.data = data;
		return openpgp.encrypt(options);
	}
}

function decrypt(data){
	decryptOptions.message = openpgp.message.readArmored(data);
	return openpgp.decrypt(decryptOptions);
}

function getTitle(html){
	var found = $(html).filter("h1").first().text().trim();
	if(found){
		return found;
	}else{
		return "Untitled"
	}
}

function addNote(noteID, noteTitle, noteColor){
	$_("[data-content='note-container']").append(`<article data-color='${noteColor}' draggable='true' data-nid='${noteID}'><div class='content' ><h2>${noteTitle}</h2></div><div class='note-actions'><span class='fa fa-eye' data-id='${noteID}' data-action='preview'></span><span class='fa-pencil fa' data-id='${noteID}' data-action='edit'></span><span class='fa-trash fa' data-id='${noteID}' data-action='delete'></span></div></article>`);
	colorNote(noteID);
}

function colorNote(id){
	if(typeof id == 'undefined'){
		$_(".list article").each(function(element){
			$_(element).style("border-color", $_(element).data("color"));
		});

		$_(".grid article").each(function(element){
			$_(element).style("background", $_(element).data("color"));
		});
	}else{
		$_(`.list [data-nid='${id}']`).style("border-color", $_(`.list [data-nid='${id}']`).data("color"));
		$_(`.grid [data-nid='${id}']`).style("background", $_(`.grid [data-nid='${id}']`).data("color"));
	}
}

function loadNotes(){
	if(key != null){
		$_("[data-content='note-container']").html("");
		$_("[data-content='welcome']").hide();
		wait("Loading your notes");
		db.transaction('r', db.note, function() {
			var ht = "";
			db.note.where("Notebook").equals(notebook).count(function(count){
				if(count <= 0){
					$_("[data-content='welcome']").show();
				}
			});
			db.note.where("Notebook").equals(notebook).each(function(item, cursor){
				var item = item;

				decrypt(item.Title).then(function(plaintext) {
					addNote(item.id, plaintext.data, item.Color);
				});
			});
		}).then(function(){
			show("notes");
		});
	}
}

function loadNotebooks(){
	return new Promise((resolve, reject) => {
		wait("Wait while your notebooks are decrypted");
		if(key != null){
			$_("[data-content='notebook-list']").html("");
			$_("[data-content='notebook-list']").append('<li data-notebook="Inbox">Inbox</li>');
			var notebooksTemp = [];
			db.transaction('r', db.notebook, function() {
				db.notebook.each(function(item, cursor){

					decrypt(item.Name).then(function(plaintext) {
						notebooksTemp.push({
							id: item.id,
							Name: plaintext.data
						});
					});

				});
			}).then(function(){
				notebooksTemp.sort(function(a, b){
					var A = a.Name.toLowerCase();
					var B = b.Name.toLowerCase();
					if (A < B){
						return -1;
					}
					if(A > B){
						return 1;
					}
					return 0;
				});
				for(var i in notebooksTemp){
					$_("[data-content='notebook-list']").append('<li data-notebook="' + notebooksTemp[i].id + '">' + notebooksTemp[i].Name + '</li>');
				}
				resolve();
			});
		}
	});
}

function loadContent(){
	loadNotebooks().then(() => {
		loadNotes();
	});
}

function getSelectionText() {
    var text = "";
    if(window.getSelection){
        text = window.getSelection().toString();
    }else if(document.selection && document.selection.type != "Control"){
        text = document.selection.createRange().text;
    }
    return text;
}

// Clean the HTML code generated by the Content Editable
function cleanHTML(html){
	return html.replace(/(<\/span>|<span style=\"line-height: 1.5em;\">)/g, '').replace(/<div>/g, '<p>').replace(/<\/div>/g, '</p>\r\n').replace(/<p><br><\/p>/g, '').replace(/&nbsp;/g, ' ');
}

$_ready(function(){

	if(navigator.onLine){
		Request.json('https://api.github.com/repos/Skrifa/Skrifa/releases/latest', {
			onload: function(data){
				if(data.response.tagname){
					if(parseInt(data.response.tagname.replace("v", "")) > parseInt(pkg.version)){
						$_("[data-action='update']").show();
					}
				}
			},
			onerror: function(error){
				console.log(error);
			}
		});
	}

	$_("[data-action='edit-notebook']").hide();
	$_("[data-action='delete-notebook']").hide();

	for(var key in Prism.languages){
		$_("[data-form='insert-snippet'] select").append("<option value='" + key + "'>"+ Text.capitalize(key) +"</option>");
	}

	if(Storage.get("PrivKey") != null){
		show("decrypt");
	}

	if(Storage.get("view") != null){

		if(Storage.get("view") == "list"){
			$_("[data-content='note-container']").removeClass("grid");
			$_("[data-content='note-container']").addClass("list");
			$_("[data-action='change-view']").removeClass("fa-th-list");
			$_("[data-action='change-view']").addClass("fa-th");
		}
	}

	if(Storage.get("theme") != null){
		$("body").removeClass();
		$_("body").addClass(Storage.get("theme"));
		$_("[data-action='change-theme']").value(Storage.get("theme"));
	}

	$_(".menu-icon").click(function(){
		if($_("[data-view='" +$_(this).data("menu") + "'] .side-nav").isVisible()){
			$("[data-view='" +$_(this).data("menu") + "'] .side-nav").removeClass("active");
		}else{
			$("[data-view='" +$_(this).data("menu") + "'] .side-nav").addClass("active");
		}
	});

	$_("[data-view='settings'] [type='reset']").click(function(){
		show("notes");
	});

});